# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DispatchRegionData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
# CNPROD 2.5.0

import src.proto.latest.RegionEntry_pb2 as RegionEntry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x44ispatchRegionData.proto\x1a\x11RegionEntry.proto\"\x87\x01\n\x12\x44ispatchRegionData\x12\x0f\n\x07retcode\x18\x01 \x01(\r\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x1d\n\x15top_sever_region_name\x18\x03 \x01(\t\x12!\n\x0bregion_list\x18\x04 \x03(\x0b\x32\x0c.RegionEntry\x12\x11\n\tstop_desc\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DispatchRegionData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DISPATCHREGIONDATA']._serialized_start=48
  _globals['_DISPATCHREGIONDATA']._serialized_end=183
# @@protoc_insertion_point(module_scope)
