# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Gateserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
# CNPROD 2.5.0



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Gateserver.proto\"\xd8\x03\n\nGateserver\x12\x0f\n\x07lua_url\x18\n \x01(\t\x12\x17\n\x0f\x65x_resource_url\x18\x0e \x01(\t\x12\x18\n\x10\x61sset_bundle_url\x18\x03 \x01(\t\x12\x11\n\x08ifix_url\x18\xd9\x08 \x01(\t\x12\x13\n\x0bregion_name\x18\x05 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0c\n\x03msg\x18\xa8\t \x01(\t\x12\x15\n\x0cifix_version\x18\x96\x0b \x01(\t\x12\x18\n\x0fmdk_res_version\x18\x95\x05 \x01(\t\x12\x1a\n\x11\x63lient_secret_key\x18\x90\x0e \x01(\t\x12\x1d\n\x15\x65nable_version_update\x18\x01 \x01(\x08\x12\x30\n(enable_design_data_bundle_version_update\x18\x07 \x01(\x08\x12\x1c\n\x13\x65vent_tracking_open\x18\x9e\x03 \x01(\x08\x12&\n\x1d\x65nable_android_middle_package\x18\xd1\x04 \x01(\x08\x12\x1b\n\x12network_diagnostic\x18\x9e\x0c \x01(\x08\x12\x19\n\x10\x65nable_watermark\x18\xb1\x0b \x01(\x08\x12\x1a\n\x11\x63lose_redeem_code\x18\xce\x0b \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Gateserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GATESERVER']._serialized_start=21
  _globals['_GATESERVER']._serialized_end=493
# @@protoc_insertion_point(module_scope)
