# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DispatchRegionData_2_4_0.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
# CNPROD 2.4.0

import src.proto.prod_2_4_0.RegionEntry_2_4_0_pb2 as RegionEntry__2__4__0__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x44ispatchRegionData_2_4_0.proto\x1a\x17RegionEntry_2_4_0.proto\"\x93\x01\n\x18\x44ispatchRegionData_2_4_0\x12\x0f\n\x07retcode\x18\x01 \x01(\r\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x1d\n\x15top_sever_region_name\x18\x03 \x01(\t\x12\'\n\x0bregion_list\x18\x04 \x03(\x0b\x32\x12.RegionEntry_2_4_0\x12\x11\n\tstop_desc\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DispatchRegionData_2_4_0_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DISPATCHREGIONDATA_2_4_0']._serialized_start=60
  _globals['_DISPATCHREGIONDATA_2_4_0']._serialized_end=207
# @@protoc_insertion_point(module_scope)
