# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegionEntry_2_4_0.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
# CNPROD 2.4.0



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17RegionEntry_2_4_0.proto\"{\n\x11RegionEntry_2_4_0\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0c\x64ispatch_url\x18\x03 \x01(\t\x12\x10\n\x08\x65nv_type\x18\x04 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x05 \x01(\t\x12\x0b\n\x03msg\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RegionEntry_2_4_0_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGIONENTRY_2_4_0']._serialized_start=27
  _globals['_REGIONENTRY_2_4_0']._serialized_end=150
# @@protoc_insertion_point(module_scope)
